#!/bin/bash

set -euo pipefail

git::is_in_repo() {
  git rev-parse HEAD >/dev/null 2>&1
}

if (! git::is_in_repo); then
  echo "Not in a git repo!"
  exit 0
fi

git add -A
git reset --hard > /dev/null 2>&1

echo 'All changes has been discarded!'
